config:
    paths:
        # Exports
        pim/job/common/edit/field/textarea: clickandmortaradvancedenrich/js/job/common/edit/field/textarea
        pim/template/export/common/edit/field/textarea: clickandmortaradvancedenrich/templates/export/common/edit/field/textarea.html
        pim/date-field: clickandmortaradvancedenrich/js/product/field/date-field
